/*
 * umsp2a.cnvendian.input.c
 *
 * This file is automatically generated by the 'createCnvEndianInput' script.
 * It contains the declarations of all CVs and TGT exports variables
 * and is used to generate the endian converters for all of these
 * variables.
 *
 * Generated on Mon Jun 21 21:26:55 EDT 2021
 */

#include "umsp2a.global.h"
#include "umsp2a.allcv.h"
#include "umsp2a.tgtex.h"
